#!/bin/bash

export CI_ROOT=`dirname "${BASH_SOURCE[0]}"`

if [ "$TRAVIS" = true ]; then
	export CI_TAG=${TRAVIS_TAG}
	export CI_COMMIT=${TRAVIS_COMMIT}
	export GH_SLUG=${TRAVIS_REPO_SLUG}

	export CI_BUILD_DIR=${TRAVIS_BUILD_DIR}

	if [ -n "${TRAVIS_RUST_VERSION:-}" ]; then
		export CI_LANG=rust
		export CI_RUST_VERSION="${TRAVIS_RUST_VERSION}"
	fi
fi

export PATH="$CI_ROOT:$CI_ROOT/$CI_LANG:$PATH"

case "$CI_LANG" in
	rust)
		export CI_RUST_ENV_HASH=$(echo "${CI_RUST_VERSION}${CARGO_FEATURES:-}" | md5sum | cut -d ' ' -f1)
		export CARGO_TARGET_DIR="$CI_BUILD_DIR/target/$CI_RUST_ENV_HASH"
		;;
esac
