#!/bin/bash

export CI_ROOT=`dirname "${BASH_SOURCE[0]}"`

if [ "$TRAVIS" = true ]; then
	export CI_GIT_TAG=${TRAVIS_TAG}
	export CI_GIT_COMMIT=${TRAVIS_COMMIT}
	export CI_GH_SLUG=${TRAVIS_REPO_SLUG}

	export CI_BUILD_DIR=${TRAVIS_BUILD_DIR}

	if [ -n "${TRAVIS_RUST_VERSION:-}" ]; then
		export CI_LANG=rust
		export CI_RUST_VERSION="${TRAVIS_RUST_VERSION}"
	fi
fi

export PATH="$CI_ROOT:$CI_ROOT/$CI_LANG:$PATH"

if [ -s "$CI_ROOT/$CI_LANG" ]; then
	source "$CI_ROOT/$CI_LANG/src"
fi

sudo() {
	`which sudo` -E "$@"
}
export -f sudo
