#!/bin/bash
set -eu

SUBCOMMAND="${1:-}"
shift

CARGO_FLAGS=()
CARGO_FEATURES=(${CARGO_FEATURES:-})

if [ -n "${CARGO_QUIET:-}" ]; then
	CARGO_FLAGS+=("-v")
fi

if [ -n "${CARGO_TARGET:-}" ]; then
	case "$SUBCOMMAND" in
		build)
			CARGO_FLAGS+=("--target" "$CARGO_TARGET")
			;;
		doc|publish) # let these through
			;;
		test)
			if [ "$CARGO_TARGET" = i686-pc-windows-gnu ]; then
				# Incompatible with mingw's unwind, and can't seem to set panic=abort in Cargo.toml for some reason??
				exit 0
			fi
			CARGO_FLAGS+=("--no-run" "--target" "$CARGO_TARGET")
			;;
		*) # run/etc can't really be done
			exit 0
			;;
	esac
fi

case "$SUBCOMMAND" in
	build|doc|run|test|bench)
		;;
	publish)
		if [ -n "$CRATES_IO_TOKEN" ]; then
			CARGO_FLAGS+=("--token=$CRATES_IO_TOKEN")
		fi
		unset CARGO_DEFAULT_FEATURES
		CARGO_FEATURES=()
		;;
	*)
		unset CARGO_DEFAULT_FEATURES
		CARGO_FEATURES=()
		;;
esac

while [ "$#" -gt 0 ]; do
	arg="$1"
	case "$arg" in
		--default-features)
			CARGO_DEFAULT_FEATURES="true"
			;;
		--no-default-features)
			CARGO_DEFAULT_FEATURES="false"
			;;
		--features)
			shift
			CARGO_FEATURES+=($1)
			;;
		--features=*)
			features=`echo "$arg" | cut -d = -f 2-`
			CARGO_FEATURES+=($features)
			;;
		--deps)
			CARGO_DOC_DEPS="true"
			;;
		--)
			CARGO_FLAGS+=("$@")
			break
			;;
		*)
			CARGO_FLAGS+=("$arg")
			;;
	esac
	shift
done

cargo_prepend() {
	if [ "${#CARGO_FLAGS[@]}" -gt 0 ]; then
		CARGO_FLAGS=("$@" "${CARGO_FLAGS[@]}")
	else
		CARGO_FLAGS=("$@")
	fi
}

if [ "${#CARGO_FEATURES[@]}" -gt 0 ]; then
	cargo_prepend "--features=${CARGO_FEATURES[*]}"
fi
if [ "${CARGO_DEFAULT_FEATURES:-true}" = "false" ]; then
	cargo_prepend "--no-default-features"
fi
if [ "$SUBCOMMAND" = "doc" -a "${CARGO_DOC_DEPS:-false}" = "false" ]; then
	cargo_prepend "--no-deps"
fi

if [ -z "${CARGO:-}" -a -n "${CI_ROOT:-}" ]; then
	CARGO=`which -a cargo | grep -v "$CI_ROOT" | head -n1`
fi

exec "${CARGO:-cargo}" "$SUBCOMMAND" "${CARGO_FLAGS[@]:+${CARGO_FLAGS[@]}}"
