#!/bin/bash

export CI_RUST_ENV_HASH=$(echo "${CI_RUST_VERSION}${CARGO_FEATURES:-}${CARGO_DEFAULT_FEATURES:-}${CARGO_TARGET:-}$(rustc --version)$(cargo --version)" | md5sum | cut -d ' ' -f1)
export CI_SUFFIX_BIN=
if [ -z "$CARGO_TARGET_DIR" ]; then
	export CARGO_TARGET_DIR="$CI_BUILD_DIR/target/$CI_RUST_ENV_HASH"
	mkdir -p "$CARGO_TARGET_DIR"
	find "$CI_BUILD_DIR/target" -mindepth 1 -maxdepth 1 -type d -ctime +10 -exec rm -rf {} \;
fi

if [ -n "${CARGO_TARGET:-}" ]; then
	rustup target add "$CARGO_TARGET"
	if [[ "$CARGO_TARGET" = *windows* ]]; then
		export CI_SUFFIX_BIN=.exe
	fi
fi

mkdir -p "$HOME/.cargo"

if which i686-w64-mingw32-gcc > /dev/null 2>&1; then
	echo "
[target.i686-pc-windows-gnu]
linker = \"$(which i686-w64-mingw32-gcc)\"
ar = \"$(which i686-w64-mingw32-ar)\"" >> "$HOME/.cargo/config"
fi

if which x86_64-w64-mingw32-gcc > /dev/null 2>&1; then
	echo "
[target.x86_64-pc-windows-gnu]
linker = \"$(which x86_64-w64-mingw32-gcc)\"
ar = \"$( which x86_64-w64-mingw32-ar)\"" >> "$HOME/.cargo/config"
fi
