name: nix install
runs:
  using: node12
  main: main.js
description: Install nix in the GitHub Actions virtual environment.
inputs:
  version:
    description: nix version to install
    required: false
    default: latest # examples: latest, 2.3, 2.2.1
  timeout:
    description: minutes to wait before failing
    required: false
    default: "2"
  daemon:
    description: Install nix in multi-user mode (currently unimplemented)
    required: false
    default: "false"
outputs:
  version:
    description: The nix version installed
  nix-path:
    description: The NIX_PATH search directories
branding:
  icon: octagon
  color: blue
