name: actions/nix
on:
  pull_request:
    paths:
    - actions/*.js
    - actions/nix/**
    - .github/workflows/action-nix.yml
    - nix/tools/install.sh
    - nix/compat.nix
    - nix/lib/cipkgs.nix
  push:
    paths:
    - actions/*.js
    - actions/nix/**
    - .github/workflows/action-nix.yml
    - nix/tools/install.sh
    - nix/compat.nix
    - nix/lib/cipkgs.nix

jobs:
  install:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        nix-version:
        - latest
        - '2.3'
        - 2.13.6
        exclude:
        - os: macos-latest
          nix-version: '2.3'
        - os: macos-latest
          nix-version: 2.13.6
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - id: nix-install
      uses: ./actions/nix/install
      with:
        version: ${{ matrix.nix-version }}
    - run: nix --version
    - run: |
        if [[ $(nix --version | cut -d ' ' -f 3) != $NIX_VERSION ]]; then
          echo ::error::Installed nix version did not match expected $NIX_VERSION
          false
        fi
      env:
        NIX_VERSION: ${{ steps.nix-install.outputs.version }}
  install-nix-path:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: ./actions/nix/install
      with:
        nix-path: nixpkgs=https://nixos.org/channels/nixos-23.05/nixexprs.tar.xz
    - uses: ./actions/nix/run
      with:
        attrs: nixpkgs.hello
        command: hello
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        nix2:
        - true
        - false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: ./actions/nix/install
    - uses: ./actions/nix/run
      with:
        attrs: nixpkgs.hello
        command: hello
        quiet: false
    - run: '! hello'
    - uses: ./actions/nix/build
      with:
        attrs: nixpkgs.hello
        add-path: true
        nix2: ${{ matrix.nix2 }}
    - run: hello
