env:
  CI_ALLOW_ROOT: '1'
  CI_CONFIG: ./tests/tasks.nix
  CI_PLATFORM: gh-actions
jobs:
  ci-check:
    name: tests-tasks check
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: ./actions/nix/install
    - id: ci-action-build
      name: nix build ci.gh-actions.configFile
      uses: ./actions/nix/build
      with:
        attrs: ci.gh-actions.configFile
        out-link: .ci/workflow.yml
    - id: ci-action-compare
      name: gh-actions compare
      uses: ./actions/nix/run
      with:
        args: -u .github/workflows/tests-tasks.yml .ci/workflow.yml
        attrs: nixpkgs.diffutils
        command: diff
  linux:
    name: tests-tasks-linux
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: ./actions/nix/install
    - id: ci-dirty
      name: nix test dirty
      uses: ./actions/nix/run
      with:
        attrs: ci.job.linux.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: ./actions/nix/run
      with:
        attrs: ci.job.linux.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: ./actions/nix/run
      with:
        attrs: ci.job.linux.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: ./actions/nix/run
      with:
        attrs: ci.job.linux.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  mac:
    name: tests-tasks-mac
    runs-on: macos-10.15
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: ./actions/nix/install
    - id: ci-dirty
      name: nix test dirty
      uses: ./actions/nix/run
      with:
        attrs: ci.job.mac.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: ./actions/nix/run
      with:
        attrs: ci.job.mac.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: ./actions/nix/run
      with:
        attrs: ci.job.mac.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: ./actions/nix/run
      with:
        attrs: ci.job.mac.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
name: tests-tasks
'on':
- push
- pull_request
